apiVersion: v1
kind: Service
metadata:
  name: traffic-generator-service
spec:
  selector:
    app: traffic_generator
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
spec:
  selector:
    matchLabels:
      app: traffic_generator
  replicas: 2
  template:
    metadata:
      labels:
        app: traffic_generator
    spec:
      containers:
      - name: container-traffic-generator
        image: traffic_generator
        imagePullPolicy: Never
