{{- if .Values.application.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.secretName }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- with .Values.application.secrets }}
  {{- range $key, $val := . }}
    "{{ tpl $key $  }}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
{{- end }}
{{- end }}
