# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: pranaysahith/metrics_generator
  tag: 0.0.6
  pullPolicy: IfNotPresent
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8000"
application:
  secretName: traffic-generator
  env:
    TEST_ID:          "1005"
    BASE_URL:         "https://glasswallsolutions.com"
    EXECUTABLE_PATH:  "/usr/bin/google-chrome-stable"
  secrets:  {}

service:
  enabled: false
  annotations: {}
  name: metrics
  type: ClusterIP
  url:
  additionalHosts:
  commonName:
  externalPort: 8000
  internalPort: 8000
ingress:
  enabled: false
  tls:
    enabled: false
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  path: /

livenessProbe: {}
readinessProbe: {}

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
scale:
  MinReplicaCount: 2
  MaxReplicaCount: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75